import type { StoreConfig } from "./adapters/types";

/**
 * Known Tiendanube stores. All use the /ar/productos/ default catalog path.
 * If a store redirects or uses a different catalog path, override it here.
 */
export const STORES: StoreConfig[] = [
  {
    slug: "grand-cru",
    name: "Grand Cru",
    platform: "tiendanube",
    baseUrl: "https://www.grandcru.com.ar",
    catalogPath: "/ar/productos/",
  },
  {
    slug: "enotek",
    name: "Enotek",
    platform: "tiendanube",
    baseUrl: "https://www.enotek.com.ar",
    catalogPath: "/ar/productos/",
  },
  {
    slug: "tonel-privado",
    name: "Tonel Privado",
    platform: "tiendanube",
    baseUrl: "https://www.tonelprivado.com",
    catalogPath: "/ar/productos/",
  },
  {
    slug: "varietal",
    name: "Varietal",
    platform: "tiendanube",
    baseUrl: "https://www.varietalvinoteca.com.ar",
    catalogPath: "/ar/productos/",
  },
  {
    slug: "rebellion",
    name: "Rebellion",
    platform: "tiendanube",
    baseUrl: "https://www.rebellion.com.ar",
    catalogPath: "/ar/productos/",
  },
  {
    slug: "wine-boutique",
    name: "Wine Boutique",
    platform: "tiendanube",
    baseUrl: "https://www.wineboutique.com.ar",
    catalogPath: "/ar/productos/",
  },
  {
    slug: "biendevinos",
    name: "Biendevinos",
    platform: "tiendanube",
    baseUrl: "https://www.biendevinos.com",
    catalogPath: "/ar/productos/",
  },
  // TODO: Dionisio — tienda.dionisioonline.com.ar devolvía NXDOMAIN el 2026-04-19.
  // El dominio bare dionisioonline.com.ar sí existe (52.200.197.31) pero no es Tiendanube.
  // Pendiente: pedir a Juan el dominio actual de la tienda.
  {
    slug: "lo-de-granado",
    name: "Lo de Granado",
    platform: "tiendanube",
    baseUrl: "https://www.lodegranado.com.ar",
    catalogPath: "/ar/productos/",
  },
  {
    slug: "1812-vinos",
    name: "1812 Vinos",
    platform: "tiendanube",
    baseUrl: "https://www.1812vinos.com.ar",
    catalogPath: "/ar/productos/",
  },
  {
    slug: "bebiendo-estrellas",
    name: "Bebiendo Estrellas",
    platform: "tiendanube",
    baseUrl: "https://www.bebiendoestrellas.com.ar",
    catalogPath: "/ar/productos/",
  },
  {
    slug: "rincon-de-vinos",
    name: "Rincón de Vinos",
    platform: "tiendanube",
    baseUrl: "https://www.rincondevinos.com.ar",
    catalogPath: "/ar/productos/",
  },
  {
    slug: "vineria-san-juan",
    name: "Vinería San Juan",
    platform: "tiendanube",
    baseUrl: "https://www.vineriasanjuan.com.ar",
    catalogPath: "/ar/productos/",
  },
  {
    slug: "vinicius",
    name: "Vinicius Vinos",
    platform: "tiendanube",
    baseUrl: "https://www.viniciusvinos.com.ar",
    catalogPath: "/ar/productos/",
  },
  {
    slug: "enoteca-privada",
    name: "Enoteca Privada",
    platform: "tiendanube",
    baseUrl: "https://www.enotecaprivada.com",
    catalogPath: "/ar/productos/",
  },
  {
    slug: "vinoteca-bodega-901",
    name: "Vinoteca Bodega 901",
    platform: "tiendanube",
    baseUrl: "https://vinotecabodega901.mitiendanube.com",
    catalogPath: "/ar/productos/",
  },
  {
    slug: "vinoteca-vito",
    name: "Vinoteca Vito",
    platform: "tiendanube",
    baseUrl: "https://vinotecavito.mitiendanube.com",
    catalogPath: "/ar/productos/",
  },
  {
    slug: "terruno",
    name: "Terruño Vinoteca",
    platform: "tiendanube",
    baseUrl: "https://terrunovinoteca.mitiendanube.com",
    catalogPath: "/ar/productos/",
  },
  {
    slug: "carlos-barroca",
    name: "Carlos Barroca",
    platform: "tiendanube",
    baseUrl: "https://vinotecaterrarum.mitiendanube.com",
    catalogPath: "/ar/productos/",
  },
  {
    slug: "vinoteca-lanus",
    name: "La Vinoteca Lanús",
    platform: "tiendanube",
    baseUrl: "https://lavinotecalanus.mitiendanube.com",
    catalogPath: "/ar/productos/",
  },
  {
    slug: "vinos-de-rios",
    name: "Vinos de Ríos",
    platform: "tiendanube",
    baseUrl: "https://vinosderios2.mitiendanube.com",
    catalogPath: "/ar/productos/",
  },
  {
    slug: "santa-barrica",
    name: "Santa Barrica",
    platform: "tiendanube",
    baseUrl: "https://www.santabarrica.com.ar",
    catalogPath: "/ar/productos/",
  },
  {
    slug: "tinte-vinos",
    name: "Tinte Vinos",
    platform: "tiendanube",
    baseUrl: "https://www.tintevinos.com.ar",
    catalogPath: "/ar/productos/",
  },
  {
    slug: "tienda-vinos",
    name: "TiendaVinos",
    platform: "tiendanube",
    baseUrl: "https://www.tiendavinos.com.ar",
    catalogPath: "/ar/productos/",
  },

  // WooCommerce stores (13). catalogPath unused — WC adapter hits Store API.
  {
    slug: "de-barricas",
    name: "De Barricas",
    platform: "woocommerce",
    baseUrl: "https://debarricas.com.ar",
    catalogPath: "/",
  },
  {
    slug: "mercado-de-vinos",
    name: "Mercado de Vinos",
    platform: "woocommerce",
    baseUrl: "https://www.mercadodevinos.com.ar",
    catalogPath: "/",
  },
  {
    slug: "don-vino",
    name: "Don Vino",
    platform: "woocommerce",
    baseUrl: "https://www.donvino.com.ar",
    catalogPath: "/",
  },
  {
    slug: "lo-de-joaquin",
    name: "Lo de Joaquín",
    platform: "woocommerce",
    baseUrl: "https://lodejoaquin.com",
    catalogPath: "/",
  },
  {
    slug: "la-enoteca",
    name: "La Enoteca",
    platform: "woocommerce",
    baseUrl: "https://laenoteca.com.ar",
    catalogPath: "/",
  },
  {
    slug: "vinos-directos",
    name: "Vinos Directos de Bodegas",
    platform: "woocommerce",
    baseUrl: "https://vinosdirectosdebodegas.com",
    catalogPath: "/",
  },
  {
    slug: "la-taverna-club",
    name: "La Taverna Club",
    platform: "woocommerce",
    baseUrl: "https://latavernaclub.com",
    catalogPath: "/",
  },
  {
    slug: "tienda-de-vinos",
    name: "Tienda de Vinos",
    platform: "woocommerce",
    baseUrl: "https://tiendadevinos.ar",
    catalogPath: "/",
  },
  {
    slug: "enofilo",
    name: "Enofilo",
    platform: "woocommerce",
    baseUrl: "https://enofilo.com.ar",
    catalogPath: "/",
  },
  {
    slug: "vino-el-salvador",
    name: "Vino El Salvador",
    platform: "woocommerce",
    baseUrl: "https://vinoelsalvador.com",
    catalogPath: "/",
  },
  {
    slug: "casa-de-vinos-mendoza",
    name: "Casa de Vinos Mendoza",
    platform: "woocommerce",
    baseUrl: "https://casadevinosmendoza.com.ar",
    catalogPath: "/",
  },
  {
    slug: "club-vinoteca",
    name: "Club Vinoteca",
    platform: "woocommerce",
    baseUrl: "https://clubvinoteca.com",
    catalogPath: "/",
  },
  {
    slug: "aldos-vinoteca",
    name: "Aldo's Vinoteca",
    platform: "shopify",
    baseUrl: "https://tienda.aldosvinoteca.com",
    catalogPath: "/products.json",
  },
  {
    slug: "galo-wines",
    name: "Galo Wines",
    platform: "woocommerce",
    baseUrl: "https://galowines.com.ar",
    catalogPath: "/",
  },
];

export function getStore(slug: string): StoreConfig | undefined {
  return STORES.find((s) => s.slug === slug);
}
